CREATE TABLE MEMBERS(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
EMAIL VARCHAR2(100),
UNAME VARCHAR2(50),
PASS VARCHAR2(50),
REGDATE DATE,
LASTLOGIN VARCHAR2(100)
)